# Generated by Django 3.2 on 2021-05-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210510_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
