# Generated by Django 3.2 on 2021-05-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_tournament_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='link',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='open_closed',
            field=models.CharField(choices=[('OPEN', '1'), ('CLOSED', '2')], default='1', max_length=20),
        ),
    ]
