# Generated by Django 3.2 on 2021-05-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_tournament_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rules',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='submission',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='timeline',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
